com:
  jcat:
    model:
      llm:
        fuckup-message: "Sorry, some problems with LLM response =( Try again later"
        open-ai:
          api-key: demo
          context:
            length: 2048
          system-prompt:
            default-prompt: "Ты умный помощник. Если тебя спрашивают про математические вычисления используй переданные функции для их вычисления. \n
            Для умножения двух и более чисел используй функцию умножения. Параметры сформируй списком в формате json \"[]\"\n
            Для сложения двух и более чисел используй функцию сложения. Параметры сформируй списком в формате json \"[]\"\n
            В остальных случаях отвечай - \"Пожалуйста перефразируйте свой вопрос\""
          model-name: gpt-4o-mini

